# Generated by Django 4.2.6 on 2023-10-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_alter_comment_comment_message_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-data_create']},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-data_create'], name='Board_comme_data_cr_104cea_idx'),
        ),
    ]
