# Generated by Django 4.2.6 on 2023-11-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0005_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m/%d', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Healers', 'Хилы'), ('DD', 'ДД'), ('Traders', 'Торговцы'), ('Gildmasters', 'Гилдмастеры'), ('Questgivers', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Tanners', 'Кожевники'), ('PotionMakers', 'Зельевары'), ('SpellMasters', 'Мастера заклинаний')], default='Tanks', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='message',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_header',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(default='', verbose_name='Текст объявления'),
        ),
    ]
