# Generated by Django 4.2.6 on 2023-11-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0006_message_files_message_photo_alter_message_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_status',
            field=models.IntegerField(choices=[(0, 'отклик отклонен'), (1, 'отклик принят'), (2, 'отклик не рассмотрен')], default=2, verbose_name='Статус отклика'),
        ),
    ]
